str="vikash"
# print(str)
# str1=input("enter your name : ")
# print("your name is : " , str1)
# print(str+str1)
print(str[0:])
print(str[1:2])
print(str[0:1])
print(str[0:])
print(str[-1:])
print(str[-1:-5])
print(str[-2:-3])
print("vikask" + " sharma") 
print(str*4)